---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1ym7n3xlwekdtjdtz0alufqea7h0sdl5afq08yvzk8y6jhjmwv5dq4qdzzk"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1ym7n3xlwekdtjdtz0alufqea7h0sdl5afq08yvzk8y6jhjmwv5dq4qdzzk"
