apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:67arECRYNfxoYp2kGMf2dNMx66qTl/A8j0753P9rwDdoKQCl,iv:JDCXNv1ITL2OpIjXAXTRboQ2pXEztMvHX8T4VBWXTI4=,tag:zyx1GvEpT72c8Nr9F3AXeQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:I017lxsBmxzPePFB1kPKOeNPwCiXeqDO6N982yL63GkgnxGEyKi9TnKeaEPMmjfFHiDlDi1iBh0vyiO5/u1KI4NOw9iH7D/9BCgzP/IEvg5UUqUyAnA09Zmhobi8BMZpF6tYyQBHG/9uING4ikDrwP+Ei+/+0gOfKb1yJg7ErD1oUJBQilclmlSVpZ9x98669iyrbx0fv4YSQ9p7Pv1UodzMrpnq2EFkUzF9xB2x,iv:4eMgYgmGO1+MfptGx9iEPQvr/O0L01e2IcluvtARZvE=,tag:LSK44fodfjPtDXhowzJUZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age197va0ftfpstdd7f0ta4mfz3jtzr4704rgztcg6g95t30uf42he5sh09j86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQnZJZmFiQ1pORTVmelZK
            NlF5MHBtK0U4dWFyVDBOclVWcHZYOVJHemxZCmRGU25oVkZNVVZPSUplOGxjQ0lq
            YnpLeElaOTl3d1RIMmhjUjhMb0hGZ00KLS0tIE9kNWNVZklZSTBMYXZzS2xjc1Nj
            M0lDWlAwOE5GdUR4NDZWbGY0d3pEQXcKgFJlhLgNni5GzApLg9C+kayF8OZjwQbL
            SgMYonF6VInZxzR8gyn7bL9C59wCbSdLfpMCLsBtc6q1XZBw3rVV3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-19T00:22:50Z"
    mac: ENC[AES256_GCM,data:Bep6tq8xJljul6/hB0xyOBs9dlUgmsA/aYHa8TRjFeApGEXYCem98W5Wv9Lha0UG0kWkMNeSjiDq2iIgk8g5a444MnEeay6qmi+iRHcBxT6FkBMXXZt60uOEN4QWe70bP9t+uchvW9pZi7saXfyzFUFX9jAEgv4SUBZ3yT9RwFA=,iv:cqmLSq3Pg17qHzF3AxK7ImN8L/yCfo67opfC3qVP1cw=,tag:c/tbb8qEZZH/HLFhnMD6cQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
