apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:OT5oNbM3G/Fh8aa5+QVqmyTbca7ezdAGeoM+4Gjhew27FBKI,iv:8vFsKrhSrTvb0qU3mK2NGQCNbhqh5U9h8k62ozIg7+8=,tag:SPSjtw4jhQj206rqPcNaRA==,type:str]
    credentials.json: ENC[AES256_GCM,data:eKFjltznvewhHfJwbA5LDgHpovP/4+tVDGm9rhnfd0E2OTONQmAIoNj7UXgmXmiYmniGVFKEHW3rpMo1j53TpfzpGeSBn5XYBWf2jNkceiNpj33EqmfEyABQJbb2LR0idDvuRjcAnN+DzUeEzHicB6cKCSudwPyPPRyZBpQR4/VSdBQQjCMP6ePMmFCjSiHWOXp2WODI1xNIDAc2F1Y9N7CiwQ1qnUmshyHLiu5d,iv:e5STmR/LJqIJwwxNrf4wz2rUrZojPD81IYfwXu6ScU8=,tag:egFhQ83LDaE6b4cT8cYCXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age197va0ftfpstdd7f0ta4mfz3jtzr4704rgztcg6g95t30uf42he5sh09j86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5L0tJUkVuZHBnbUh3Skxx
            ODQ0c3NKazJiTjliUEpQVzU4aksyMXo4RTBVClhnakFOeWxDWWJQMUVHUVZoS0JP
            SFhsKzIxNkdBS2h0TjFCL29xUkdLbXcKLS0tIG1WbzBPV0RPNC9tQkx1Wk0yMWpH
            SkRoUnExdGw4d1VnT0NyU3lkM3QvUmcK0QgCRbLgylcx0V+CsF8uMlxaf9qKXuec
            FZN9BsNfJPjPi3zqmI9FqOlEZLRyCBFdSLMkHJftjAoSyHE54ZXRGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-18T22:10:02Z"
    mac: ENC[AES256_GCM,data:ei8vFNJuMTUtUkbmJuRXbWIOqOmkTf6XVsLcHsxliypHopL/d+r8mDnFJ8DEQkjyfLJ/V5OuK3vW7+RNKjmaH7MuKgnsZT9AQPzceAmua7y8hmb3di7A2L1ZjMkGXrUNORSdsT2y5ssd5zEPuSNbhMk7mkvYzfeNHccs6AugxxQ=,iv:LI1JwEjWP7EZb8hAyj5ebYkwjJUITJ4dukOvGtc3gs0=,tag:3fdxBtRCCNDK2MtbneG3hg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
