# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:vEWJs5ExLMHqNDKkZFLvbViYHFnbhPGIUiD03D9nNwRtcvgPWLKSounM3eVYZ9EDRNvKwU6isqvX6+RVbZMI0vAGItBFmdMeaIGrXwCOJ9q7hn25K8XZMFjkeiaQlW5YPsf7l9uniWoHfMt9f6BRxyf+ykmWmGlIST7YQMkTsL4RQH88rxW+vZfDYlWVmnHVHtoNODItw8qmelqxvYnIxLZyRt2ZxMcfwvEl+BAiXhJHBEIdJFhD348bqDPcBcjWSEhWY/3I+FTkwkDmg15HCLy35BWqGI2HX+eXWGt656M4ZQrlqg4yb5bwj89DIDqJ0Ul4U6T3hH9/qzVZoSNRLA3zmXHx5OiixYLt1fudKyBauu7kuAxIw0duGhj8Iuty476n6tIBEY9dYBM0wC19AmEmk+iOYA3zui4POgufL6mhPbsGRsb8+npeJLzgODAnhVWmQbmrj/LMHe+t5p5EEWsWryVlLEdtfSS8CasQap6pFRfu95xIUXEA6JWzUQi03Ph6JtPk2aTA6qCLb8nSFrfmxlsWVdkeOkHzaC6YWDsH787vlWgmLOgUMj564+3br9ZXNYYqAihsMGrEIcomG8GImqzfHR+pLrEV8cEjvIVFznwSV1R2np33A2dizp87+gbxLhZQPqslBXQV4XI2yHews54oC2aFJdJbJb+xktMA1GReEmpcvhOBWaBUGN9lDUojLTOWV/PE+I6voCjQ/Q4pUujt1CS4HPjJZF6BvxSK0SVN7HPktebPOJ5Ji1mN8uiLOT0ORf3I2FAr5MloHT+rH2gbdTVBLoI5ULydteZGRk/zx9pnN5gsx0F1fi7Sa8si6GZMBAmz9397XweLme0cTj1OLY2NjE0RLNe9f6Eg90rTzSLP/ZirLi8OGL5fpa7iJFGuMi8sufXmfHP+LUgk718M4Z53eAiIdLnsNGZUpjUFLhJglLE2LIR+JD5zPlZIvLVtrWTAv1TyFH400rnd6a1F64cVZT4RDj+efJMt9XZAr0vBoGBTq41XKiCdeMWCyVPMIE1Yn3QqwTDv7LxWIySlUzR2FU2bpHKUyML+OF0b5QCZj6B+VWYbWGwjOqa9Pm7MjCZ8BJrIFS1GA26LW1JuIdQ8iKa10h7PwozLaRu5rUO2js+uxagCjFHDhLyv6/cStgdzAeK2/kVMUnQOY+QgSRYJvSDs1PDl+vam3/1EPch5z7P1by+4R/ee8CRvCXtgIBOaNLflDVS44OjNhQRnhkgLc4jdzEFv1uqNv3hyBJjVZznRvhSCwLGoDvMkcrCg9OkhAivYm8zVRhq47zDkPfhCVT6w1vop9MtnF7Cw9zsyEaDdBGyUWpHz3FrVnAa2AsuN5pCSpmHa+SadNgxwF9ho2kM44UHF+YRU8FJiaAHnMJ8eUjP4+Bud5jlkVspT8DvX+gAFFegTWhJXcl8q5TSdVpR1zlcypLkxnpRHgOl0H5coVCNlEZ2AmiilgEZXNSsbQXxLDxOkWrNc/5lQQ2fL653cdJiQBVy+1jVPorEQJeorPEo2K6Zb9O9tGUEJ6oF618mL078FeVnxrYmKGsVAimdCZvwV+Lmmkwn9oKoH729HqvB7M1xGBrTj0ta6y5ik1IE9wH9Lib8Kpjc7XQpVZQhy8Ko9fDjnUAI2pACmuGoAivyne5PhRL0+I5+//qfXkO1RMsSzHNz9MQq5XqcAfDuxO38war6G2fux1blRaHned3RcQGDGd/rSQZxSXnuE11mI4VpBA0tfVLqpgV4NlY0ZivD0wwRfrsp5emrqz3ziQJH+hZw+rSMYfAqtP+L2pn92cSEpo40BafLhiQjZZwNOh5s0cvV3MYgLbrEO2CbXipsKRxgnRuDhUE8RQLPKKocivRaoCfdSuRgxi6ZA3UqECBqHeuZStHpKzPv80dLwPWQ0XF0B7ZWjr77Am/OnrTZB,iv:DPZgiiwtpzRrkGv0yr6hdSAnBQ+fN0+eZLpEI6tBVIc=,tag:qU5LkLhob5bAPFidKz75kw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age197va0ftfpstdd7f0ta4mfz3jtzr4704rgztcg6g95t30uf42he5sh09j86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweVBjaWUyMkVJeUFGUXFk
            eEZxY3Y4Tm13S0xNcnBsbER6YVlreG5ZckNzCm1rQTBTNUp2by9CY2xBaU5DZW1j
            S09MdEs5RTY4aUtaYzFUejlsRk12VWcKLS0tIGhhemdTVG9sU2hPTGJCQUdBcWlj
            cnlzalEvUXlTRGg0R0ovUWZhN01XQVEK1Pbe8NySdACh54+ciQe1KXcJO/3krqcB
            NZ0ZX/nzpjAk9A6SPG1tHNz0SSVF931e3Q1xj0p68CZFldFgubdFpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-18T16:12:07Z"
    mac: ENC[AES256_GCM,data:P+kvGPspZ2IiOhOfTGoIAfayg5udpi0sGau+7r+TG+3IZLGtOqFijb4iJ4ScWUiOoIOXIhRsciCfk1Zeee2rzi1z5kOEqfxg4Lfm8bpzN+6sW+VsJn5GLOaEQCbTyrLsWt34iZrUHETR7VA6EWGdHqSO6xxNEaWJ3l3KCUktlgg=,iv:Ig0GzOxQFE001W3hSF4yMyHARwd+S5H5NwOj8vxTVEo=,tag:t3ZS/JaA4ZmeLZ5beUUuOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:DDC7Dh+iDbn+QXnsILyzhmYldxxEK1qiA35+bRJTGcbOsHckHiHlFuPz6TY9LWQydTZatSl7N8YbO9Kq7RhABGUi2YymWv/3p0WMZRR8lauaIE9fFd+b3/bk9tfRLGPN9/18DyYbKsbsrawwdHq5Lw/E0Euw0INqSb/XVzOygo1rHiwBcMP/z67ILiJTXTqVtKk0JT2wDB0kcNm189El7tcm8evg5uMNqGXIS1BQIi4jvQuWiRczwfy+i5+FbrhOryuID8eDypwxpIV2qKePf4iGU39g/hwazQBeD+bpbhUfHElvDHCav2I0OfMzh4erIGaUM06V9QDEltCZgwx6shMbVy24M6DTo/jZgRfhctC48s917RXaYYrOPKftO+NZ27+EvMCqTgsSVGG3V/RkpYUHP9avJHCfSKUYduTC95nCDn76DRpv57r2fUMvJrrSVCTRKH+WQYJMwiLOiGnPl/xi76l4+h+K//APd5kKdYNcY+imuuh5QGVYMhYB/izHQ37oqg+axIy7lCNqbARLG26wBDeLqH+OeHppboQMSZJdhvkpw729BF5PLD3AVRHL2/VpKaExGwkp9zj3UJQtBXH7ftkWzSy1SN7qZz7VC1RFFYtQ0U91WVTozXEe+0sirYKQrr52qnUadJGibFB40tqpF8BZv5+5GsfXqKa5VTCmP6SjgG1730tMEDUVTWHl/shDadav7vTyQ05JRHneujnTx9Q/ZJy/PYE9CTiyeef+N4Kp0sG0TkfaWqcR0VYRpYmFtIJPCkA2sIQecCGm1ZlBMTlYpHfCdR64xCezgOF+lexwlX3gEgqT0vTdqM41GUFcs34Hm7/RlE7K4qiXhTn/,iv:yphteDQMA+1RzueI1drzScI8r8I7AMvXecMERHNF0X8=,tag:IUcFL0EDHrWCvkFwJljfPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age197va0ftfpstdd7f0ta4mfz3jtzr4704rgztcg6g95t30uf42he5sh09j86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweVBjaWUyMkVJeUFGUXFk
            eEZxY3Y4Tm13S0xNcnBsbER6YVlreG5ZckNzCm1rQTBTNUp2by9CY2xBaU5DZW1j
            S09MdEs5RTY4aUtaYzFUejlsRk12VWcKLS0tIGhhemdTVG9sU2hPTGJCQUdBcWlj
            cnlzalEvUXlTRGg0R0ovUWZhN01XQVEK1Pbe8NySdACh54+ciQe1KXcJO/3krqcB
            NZ0ZX/nzpjAk9A6SPG1tHNz0SSVF931e3Q1xj0p68CZFldFgubdFpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-18T16:12:07Z"
    mac: ENC[AES256_GCM,data:P+kvGPspZ2IiOhOfTGoIAfayg5udpi0sGau+7r+TG+3IZLGtOqFijb4iJ4ScWUiOoIOXIhRsciCfk1Zeee2rzi1z5kOEqfxg4Lfm8bpzN+6sW+VsJn5GLOaEQCbTyrLsWt34iZrUHETR7VA6EWGdHqSO6xxNEaWJ3l3KCUktlgg=,iv:Ig0GzOxQFE001W3hSF4yMyHARwd+S5H5NwOj8vxTVEo=,tag:t3ZS/JaA4ZmeLZ5beUUuOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
