---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unpoller
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unpoller-secret
    template:
      engineVersion: v2
      data:
        UP_UNIFI_DEFAULT_USER: "{{ .UNIFI_POLLER_USER }}"
        UP_UNIFI_DEFAULT_PASS: "{{ .UNIFI_PASSWORD }}"
  dataFrom:
    - extract:
        key: unifi
