---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Paperless
        PAPERLESS_DBHOST: &dbhost postgres1-rw.databases.svc.cluster.local
        PAPERLESS_DBNAME: &dbname paperless
        PAPERLESS_DBUSER: &dbuser "{{ .POSTGRES_USER }}"
        PAPERLESS_DBPASS: &dbpass "{{ .POSTGRES_PASS }}"
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: paperless
    - extract:
        key: cloudnative-pg-superuser
