apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:o/1L7rMMrMa+oNvCYMnosK97eGgLci2qMOhjDBqsK18=,iv:ppM024Dk2QQAMp9UrxrK8FYpKAtRdzcQ2/oWlycBO5o=,tag:KdwbhV/yUqvo0MXBpqMj2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age197va0ftfpstdd7f0ta4mfz3jtzr4704rgztcg6g95t30uf42he5sh09j86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaGpqUnp3NGROdlBCVUNl
            Wk1VcXhSTHU3SXZqMnJGaUpCbWZDWTBuNW4wCjJSeGo5K2ZSZ3J6Q0UwMEpiMWJ2
            U1F4Q3pRRGIySjRIUjBjbmFxZlVXbjAKLS0tIGIyK1QvMzFudDRwVWtnaFQ2d1lX
            T2h3WHJIRkFWdEJiNlRyNU9iZm8vdG8KQm2Ih/9iSfrqjpn0rUsi3XdIN0nPFaM5
            lgnvOaDYhY1ft79AY7NPvP+K9/0+s3DsweYVHNIHJDOc1zXpTUJ2RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-18T22:10:02Z"
    mac: ENC[AES256_GCM,data:j64Q+Jh9aK3rMZKoIUFkw3jcywVaDxZ5c50p6wQFKnn7Q0nBRDbrHgL89qu7kY7/PYVcCfT6xnGLujWsLmM4EC7/skHo7azPSqAC01MehssbV5TSFrMSFqyLSrBHJUxvu+HF/dOKZhq9dCFr4uToTpPCMp0EEqwT1XVcV/p0Cm4=,iv:FBuhOn99Mf2860NF1ME7HSr1ixjfDDMaa4hkSBY70ZE=,tag:A7+YUA7/iL9jd7aAWTFjZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
